# Generated by Django 4.0.2 on 2022-05-13 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('course_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=40)),
                ('course_img', models.ImageField(default=None, upload_to='company/images')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='topic',
            fields=[
                ('topic_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=50)),
                ('topic_data', models.CharField(max_length=4294967295)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('course_name', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='company.course')),
            ],
        ),
    ]
