# Generated by Django 4.0.2 on 2022-05-13 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='course_name',
        ),
    ]
