# Generated by Django 4.0.2 on 2022-05-13 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_topic_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='course_rel',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='company.course'),
        ),
    ]
