# Generated by Django 4.0.2 on 2022-05-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_topic_course_rel'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='related_course',
            field=models.CharField(default='', max_length=200),
        ),
    ]
