# Generated by Django 4.0.2 on 2022-05-13 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_course_related_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='related_course',
        ),
    ]
