# Generated by Django 4.0.2 on 2022-05-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_remove_course_related_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='related_course',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
