# Generated by Django 4.0.2 on 2022-05-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_topic_related_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='related_course',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
