# Generated by Django 4.0.2 on 2022-09-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_topic_related_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_data',
            field=models.TextField(),
        ),
    ]
